import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const src = join(__dirname, '../src');
const workbench = readFileSync(join(src, 'pages/workflow/ProjectGoalWorkbench.tsx'), 'utf8');
const hook = readFileSync(join(src, 'pages/agent/hooks/useGoalWorkflow.ts'), 'utf8');
const stream = readFileSync(join(src, 'pages/agent/hooks/useGoalProgressStream.ts'), 'utf8');
const nav = readFileSync(join(src, 'pages/agent/components/BatchChapterNav.tsx'), 'utf8');
const workspace = readFileSync(join(src, 'pages/agent/components/ChapterWorkspace.tsx'), 'utf8');
const inspector = readFileSync(join(src, 'pages/agent/components/GoalInspector.tsx'), 'utf8');
const composer = readFileSync(join(src, 'pages/agent/components/ReworkComposer.tsx'), 'utf8');
const statusCard = readFileSync(join(src, 'components/production/BookProductionStatusCard.tsx'), 'utf8');
const layoutCss = readFileSync(join(src, 'styles/layout.css'), 'utf8');
const goalCss = readFileSync(join(src, 'styles/goal-console.css'), 'utf8');
const productionCss = readFileSync(join(src, 'styles/book-production.css'), 'utf8');
const api = readFileSync(join(src, 'api/index.ts'), 'utf8');
const agentPage = readFileSync(join(src, 'pages/AgentPage.tsx'), 'utf8');
const workflowPage = readFileSync(join(src, 'pages/WorkflowPage.tsx'), 'utf8');
const app = readFileSync(join(src, 'App.tsx'), 'utf8');
const rail = readFileSync(join(src, 'components/layout/Rail.tsx'), 'utf8');

assert.match(workbench, /BatchChapterNav/);
assert.match(workbench, /ChapterWorkspace/);
assert.match(workbench, /GoalInspector/);
assert.match(workbench, /ReworkComposer/);
assert.match(workbench, /useGoalWorkflow/);
assert.match(workbench, /candidateCommandsDisabled/);
assert.match(workflowPage, /ProjectGoalWorkbench/);
assert.match(workflowPage, /workflow\.latestGoalId/);
assert.match(hook, /sourceSessionId/);
assert.match(stream, /event\.type\.startsWith\('goal_'\)/);
assert.match(stream, /data\?\.goalId !== goalId/);
assert.match(nav, /chapterNumber/);
assert.match(workspace, /DraftArtifact|draftContent/);
assert.match(workspace, /ReviewArtifacts|reviewArtifacts/);
assert.match(inspector, /TotalCostLimit|totalCostLimit/);
assert.match(inspector, /pauseGoal|resumeGoal|cancelGoal/);
assert.match(inspector, /changeExecutionStrategy|continueBatch/);
assert.match(inspector, /<details className="goal-task-list">/);
assert.match(composer, /selectionStart|selectionEnd/);
assert.match(composer, /reworkGoalChapter/);
assert.match(statusCard, /Agent 生产决策/);
assert.match(statusCard, /用户在工作流验收/);
assert.match(statusCard, /查看实时工作流/);
assert.match(api, /getLatestProjectGoalWorkflowStatus/);
assert.match(api, /getGoalWorkflowStatus/);
assert.match(api, /reworkGoalChapter/);
assert.match(api, /acceptGoalChapter/);
assert.match(api, /mergeGoalPrefix/);
assert.match(api, /cancelGoal/);
assert.match(api, /confirmGoalWorkflow/);
assert.match(agentPage, /BookProductionStatusCard/);
assert.match(agentPage, /getLatestProjectGoalWorkflowStatus/);
assert.match(agentPage, /navigate\(`\/workflow\/\$\{encodeURIComponent\(currentProjectId\)\}`\)/);
assert.doesNotMatch(agentPage, /navigate\(`\/goal\//);
assert.doesNotMatch(app, /GoalConsolePage|path="\/goal/);
assert.doesNotMatch(rail, /Goal 工作台|path:\s*'\/goal'/);
assert.match(layoutCss, /\.desk\s*\{[^}]*min-width:\s*0;[^}]*width:\s*100%;/s);
assert.match(goalCss, /@media\s*\(max-width:\s*760px\)\s*\{[\s\S]*?\.goal-console-center,\s*\.goal-inspector\s*\{[^}]*min-height:\s*auto;[^}]*flex:\s*0\s+0\s+auto;[^}]*overflow:\s*visible;[^}]*max-height:\s*none;/);
assert.match(productionCss, /\.project-goal-workbench-grid/);
assert.match(productionCss, /\.book-production-decision-grid/);
