import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '../src/pages/agent');
const page = readFileSync(join(root, 'GoalConsolePage.tsx'), 'utf8');
const hook = readFileSync(join(root, 'hooks/useGoalWorkflow.ts'), 'utf8');
const stream = readFileSync(join(root, 'hooks/useGoalProgressStream.ts'), 'utf8');
const nav = readFileSync(join(root, 'components/BatchChapterNav.tsx'), 'utf8');
const workspace = readFileSync(join(root, 'components/ChapterWorkspace.tsx'), 'utf8');
const inspector = readFileSync(join(root, 'components/GoalInspector.tsx'), 'utf8');
const composer = readFileSync(join(root, 'components/ReworkComposer.tsx'), 'utf8');
const layoutCss = readFileSync(join(__dirname, '../src/styles/layout.css'), 'utf8');
const goalCss = readFileSync(join(__dirname, '../src/styles/goal-console.css'), 'utf8');
const api = readFileSync(join(__dirname, '../src/api/index.ts'), 'utf8');
const agentPage = readFileSync(join(__dirname, '../src/pages/AgentPage.tsx'), 'utf8');

assert.match(page, /BatchChapterNav/);
assert.match(page, /ChapterWorkspace/);
assert.match(page, /GoalInspector/);
assert.match(page, /ReworkComposer/);
assert.match(page, /useGoalWorkflow/);
assert.match(hook, /sourceSessionId/);
assert.match(stream, /event\.type\.startsWith\('goal_'\)/);
assert.match(stream, /data\?\.goalId !== goalId/);
assert.doesNotMatch(page, /sessionId="goal-console"/);
assert.match(nav, /chapterNumber/);
assert.match(workspace, /DraftArtifact|draftContent/);
assert.match(workspace, /ReviewArtifacts|reviewArtifacts/);
assert.match(page, /candidateCommandsDisabled/);
assert.match(inspector, /TotalCostLimit|totalCostLimit/);
assert.match(inspector, /pauseGoal|resumeGoal|cancelGoal/);
assert.match(inspector, /canPause/);
assert.match(inspector, /canResume/);
assert.match(inspector, /canCancel/);
assert.match(inspector, /<details className="goal-task-list">/);
assert.match(layoutCss, /\.desk\s*\{[^}]*min-width:\s*0;[^}]*width:\s*100%;/s);
assert.match(layoutCss, /@media\s*\(max-width:\s*1180px\)\s*\{[\s\S]*?\.studio-shell\s*\{[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\);[^}]*height:\s*auto;[^}]*min-height:\s*100vh;[^}]*overflow:\s*visible;/);
assert.match(layoutCss, /@media\s*\(max-width:\s*1180px\)\s*\{[\s\S]*?\.rail\s*\{[^}]*min-width:\s*0;/);
assert.match(layoutCss, /@media\s*\(max-width:\s*1180px\)\s*\{[\s\S]*?\.rail\s*>\s*nav\s*\{[^}]*min-width:\s*0;[^}]*flex:\s*1;[^}]*overflow:\s*hidden;/);
assert.match(layoutCss, /@media\s*\(max-width:\s*1180px\)\s*\{[\s\S]*?\.rail-nav\s*\{[^}]*min-width:\s*0;[^}]*overflow-x:\s*auto;/);
assert.match(layoutCss, /@media\s*\(max-width:\s*760px\)\s*\{[\s\S]*?\.rail\s*\{[^}]*display:\s*grid;[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\)\s+auto;/);
assert.match(layoutCss, /@media\s*\(max-width:\s*760px\)\s*\{[\s\S]*?\.rail\s*>\s*nav\s*\{[^}]*grid-column:\s*1\s*\/\s*-1;[^}]*grid-row:\s*2;/);
assert.match(layoutCss, /@media\s*\(max-width:\s*760px\)\s*\{[\s\S]*?\.stage-item\s*\{[^}]*white-space:\s*nowrap;/);
assert.match(layoutCss, /@media\s*\(max-width:\s*760px\)\s*\{[\s\S]*?\.topbar-center\s*\{[^}]*position:\s*static;[^}]*grid-column:\s*1\s*\/\s*-1;[^}]*width:\s*100%;[^}]*max-width:\s*100%;[^}]*transform:\s*none;[^}]*white-space:\s*nowrap;/);
assert.match(goalCss, /@media\s*\(max-width:\s*760px\)\s*\{[\s\S]*?\.goal-console-center,\s*\.goal-inspector\s*\{[^}]*min-height:\s*auto;[^}]*flex:\s*0\s+0\s+auto;[^}]*overflow:\s*visible;[^}]*max-height:\s*none;/);
assert.match(goalCss, /@media\s*\(max-width:\s*760px\)\s*\{[\s\S]*?\.goal-chapter-workspace\s*\{[^}]*min-height:\s*210px;/);
assert.match(composer, /selectionStart|selectionEnd/);
assert.match(composer, /reworkGoalChapter/);
assert.match(api, /getGoalWorkflowStatus/);
assert.match(api, /getGoalChapter/);
assert.match(api, /reworkGoalChapter/);
assert.match(api, /acceptGoalChapter/);
assert.match(api, /mergeGoalPrefix/);
assert.match(api, /cancelGoal/);
assert.match(api, /confirmGoalWorkflow/);
assert.match(agentPage, /directorProposal/);
assert.match(agentPage, /goalBudgetLimit/);
assert.match(agentPage, /confirmGoalWorkflow/);
assert.match(agentPage, /navigate\(`\/goal\/\$\{encodeURIComponent\(goalId\)\}`\)/);
