// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TM.Web.NovelAgentWeb.Data;

#nullable disable

namespace TM.Web.NovelAgentWeb.Migrations
{
    [DbContext(typeof(NovelAgentDbContext))]
    [Migration("20260608114349_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.AgentMemory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<string>("MemoryType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("memory_type");

                    b.Property<string>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId", "ProjectId")
                        .HasDatabaseName("idx_memories_user_project");

                    b.ToTable("agent_memories", (string)null);
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.AgentSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<string>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<string>("SessionData")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_data");

                    b.Property<string>("Title")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("新会话")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("agent_sessions", (string)null);
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.Chapter", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("chapter_number");

                    b.Property<string>("ContentPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content_path");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("draft")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("VolumeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("volume_id");

                    b.Property<int>("WordCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("word_count");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("idx_chapters_project");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_chapters_status");

                    b.HasIndex("VolumeId")
                        .HasDatabaseName("idx_chapters_volume");

                    b.ToTable("chapters", (string)null);
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.Character", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("DetailJsonPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("detail_json_path");

                    b.Property<string>("FirstAppearanceChapterId")
                        .HasColumnType("TEXT")
                        .HasColumnName("first_appearance_chapter_id");

                    b.Property<string>("Identity")
                        .HasColumnType("TEXT")
                        .HasColumnName("identity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Personality")
                        .HasColumnType("TEXT")
                        .HasColumnName("personality");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("FirstAppearanceChapterId");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("idx_characters_project");

                    b.ToTable("characters", (string)null);
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.Foreshadow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int?>("Importance")
                        .HasColumnType("INTEGER")
                        .HasColumnName("importance");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("PayoffChapterId")
                        .HasColumnType("TEXT")
                        .HasColumnName("payoff_chapter_id");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<string>("SetupChapterId")
                        .HasColumnType("TEXT")
                        .HasColumnName("setup_chapter_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("planned")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("PayoffChapterId");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("idx_foreshadows_project");

                    b.HasIndex("SetupChapterId");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_foreshadows_status");

                    b.ToTable("foreshadows", (string)null);
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.KnowledgeBase", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("entry_type");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<int>("UsageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("usage_count");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("knowledge_base", (string)null);
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.Material", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<string>("ContentType")
                        .HasColumnType("TEXT")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT")
                        .HasColumnName("file_path");

                    b.Property<string>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("idx_materials_project");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_materials_user");

                    b.ToTable("materials", (string)null);
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.NovelProject", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CoreHook")
                        .HasColumnType("TEXT")
                        .HasColumnName("core_hook");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("cover_image_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Genre")
                        .HasColumnType("TEXT")
                        .HasColumnName("genre");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("draft")
                        .HasColumnName("status");

                    b.Property<string>("StorageProjectName")
                        .HasColumnType("TEXT")
                        .HasColumnName("storage_project_name");

                    b.Property<string>("SubGenre")
                        .HasColumnType("TEXT")
                        .HasColumnName("sub_genre");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<int>("WordCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("word_count");

                    b.HasKey("Id");

                    b.HasIndex("StorageProjectName")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("novel_projects", (string)null);
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("ApiCallQuota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(10000)
                        .HasColumnName("api_call_quota");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<int>("StorageQuotaMb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(5120)
                        .HasColumnName("storage_quota_mb");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.UserSettings", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<bool>("AgentAutoContinue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("agent_auto_continue");

                    b.Property<string>("AgentDefaultRisk")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Medium")
                        .HasColumnName("agent_default_risk");

                    b.Property<int>("AgentMaxAutoSteps")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(12)
                        .HasColumnName("agent_max_auto_steps");

                    b.Property<int>("DefaultChapterWordCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(3000)
                        .HasColumnName("default_chapter_word_count");

                    b.Property<string>("DefaultGenre")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("玄幻")
                        .HasColumnName("default_genre");

                    b.Property<string>("EmbeddingModel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("bge-small-zh-v1.5")
                        .HasColumnName("embedding_model");

                    b.Property<string>("EmbeddingProvider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("local")
                        .HasColumnName("embedding_provider");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("zh-CN")
                        .HasColumnName("language");

                    b.Property<string>("LlmApiKeyEncrypted")
                        .HasColumnType("TEXT")
                        .HasColumnName("llm_api_key_encrypted");

                    b.Property<string>("LlmBaseUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("llm_base_url");

                    b.Property<int>("LlmMaxTokens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(4096)
                        .HasColumnName("llm_max_tokens");

                    b.Property<string>("LlmModel")
                        .HasColumnType("TEXT")
                        .HasColumnName("llm_model");

                    b.Property<string>("LlmProvider")
                        .HasColumnType("TEXT")
                        .HasColumnName("llm_provider");

                    b.Property<float>("LlmTemperature")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.7f)
                        .HasColumnName("llm_temperature");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("dark")
                        .HasColumnName("theme");

                    b.HasKey("UserId");

                    b.ToTable("user_settings", (string)null);
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.Volume", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<int>("VolumeNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("volume_number");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("volumes", (string)null);
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.WorldSetting", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<string>("Rules")
                        .HasColumnType("TEXT")
                        .HasColumnName("rules");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("world_settings", (string)null);
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.AgentMemory", b =>
                {
                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.NovelProject", "Project")
                        .WithMany("AgentMemories")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.User", "User")
                        .WithMany("AgentMemories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.AgentSession", b =>
                {
                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.NovelProject", "Project")
                        .WithMany("AgentSessions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.User", "User")
                        .WithMany("AgentSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.Chapter", b =>
                {
                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.NovelProject", "Project")
                        .WithMany("Chapters")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.Volume", "Volume")
                        .WithMany("Chapters")
                        .HasForeignKey("VolumeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Project");

                    b.Navigation("Volume");
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.Character", b =>
                {
                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.Chapter", "FirstAppearanceChapter")
                        .WithMany("CharactersFirstAppearance")
                        .HasForeignKey("FirstAppearanceChapterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.NovelProject", "Project")
                        .WithMany("Characters")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FirstAppearanceChapter");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.Foreshadow", b =>
                {
                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.Chapter", "PayoffChapter")
                        .WithMany("ForeshadowsPayoff")
                        .HasForeignKey("PayoffChapterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.NovelProject", "Project")
                        .WithMany("Foreshadows")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.Chapter", "SetupChapter")
                        .WithMany("ForeshadowsSetup")
                        .HasForeignKey("SetupChapterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PayoffChapter");

                    b.Navigation("Project");

                    b.Navigation("SetupChapter");
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.KnowledgeBase", b =>
                {
                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.NovelProject", "Project")
                        .WithMany("KnowledgeBases")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.Material", b =>
                {
                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.NovelProject", "Project")
                        .WithMany("Materials")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.User", "User")
                        .WithMany("Materials")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.NovelProject", b =>
                {
                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.User", "User")
                        .WithMany("NovelProjects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.UserSettings", b =>
                {
                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.User", "User")
                        .WithOne("UserSettings")
                        .HasForeignKey("TM.Web.NovelAgentWeb.Data.Entities.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.Volume", b =>
                {
                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.NovelProject", "Project")
                        .WithMany("Volumes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.WorldSetting", b =>
                {
                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.NovelProject", "Project")
                        .WithMany("WorldSettings")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.Chapter", b =>
                {
                    b.Navigation("CharactersFirstAppearance");

                    b.Navigation("ForeshadowsPayoff");

                    b.Navigation("ForeshadowsSetup");
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.NovelProject", b =>
                {
                    b.Navigation("AgentMemories");

                    b.Navigation("AgentSessions");

                    b.Navigation("Chapters");

                    b.Navigation("Characters");

                    b.Navigation("Foreshadows");

                    b.Navigation("KnowledgeBases");

                    b.Navigation("Materials");

                    b.Navigation("Volumes");

                    b.Navigation("WorldSettings");
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.User", b =>
                {
                    b.Navigation("AgentMemories");

                    b.Navigation("AgentSessions");

                    b.Navigation("Materials");

                    b.Navigation("NovelProjects");

                    b.Navigation("UserSettings");
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.Volume", b =>
                {
                    b.Navigation("Chapters");
                });
#pragma warning restore 612, 618
        }
    }
}
