// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TM.Web.NovelAgentWeb.Data;

#nullable disable

namespace TM.Web.NovelAgentWeb.Migrations
{
    [DbContext(typeof(NovelAgentDbContext))]
    [Migration("20260613054958_AddUnifiedMemoryPipeline")]
    partial class AddUnifiedMemoryPipeline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.AgentChatSummary", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("EndTurn")
                        .HasColumnType("INTEGER")
                        .HasColumnName("end_turn");

                    b.Property<string>("KeyDecisionsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("key_decisions_json");

                    b.Property<string>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<int>("StartTurn")
                        .HasColumnType("INTEGER")
                        .HasColumnName("start_turn");

                    b.Property<string>("SummaryType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("summary")
                        .HasColumnName("summary_type");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("agent_chat_summaries", (string)null);
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.AgentChatTurn", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CompressedIntoSummaryId")
                        .HasColumnType("TEXT")
                        .HasColumnName("compressed_into_summary_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<int>("TokenCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("token_count");

                    b.Property<int>("TurnIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("turn_index");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.HasIndex("SessionId", "TurnIndex")
                        .IsUnique();

                    b.ToTable("agent_chat_turns", (string)null);
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.AgentMemory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("MemoryKey")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasColumnName("memory_key");

                    b.Property<string>("MemoryType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("memory_type");

                    b.Property<string>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId", "ProjectId")
                        .HasDatabaseName("idx_memories_user_project");

                    b.ToTable("agent_memories", (string)null);
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.AgentMemoryEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("MemoryKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("memory_key");

                    b.Property<string>("MemoryScope")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("memory_scope");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}")
                        .HasColumnName("payload_json");

                    b.Property<string>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<string>("RunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("run_id");

                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_type");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("trigger_type");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RunId");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("agent_memory_events", (string)null);
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.AgentMemoryVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("scope");

                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId", "ProjectId", "SessionId", "Scope")
                        .IsUnique();

                    b.HasIndex("UserId", "Scope")
                        .IsUnique()
                        .HasDatabaseName("IX_agent_memory_versions_user_scope_global")
                        .HasFilter("project_id IS NULL AND session_id IS NULL");

                    b.HasIndex("UserId", "ProjectId", "Scope")
                        .IsUnique()
                        .HasDatabaseName("IX_agent_memory_versions_user_project_scope")
                        .HasFilter("project_id IS NOT NULL AND session_id IS NULL");

                    b.HasIndex("UserId", "SessionId", "Scope")
                        .IsUnique()
                        .HasDatabaseName("IX_agent_memory_versions_user_session_scope")
                        .HasFilter("project_id IS NULL AND session_id IS NOT NULL");

                    b.HasIndex("UserId", "ProjectId", "SessionId", "Scope")
                        .IsUnique()
                        .HasDatabaseName("IX_agent_memory_versions_user_project_session_scope_not_null")
                        .HasFilter("project_id IS NOT NULL AND session_id IS NOT NULL");

                    b.ToTable("agent_memory_versions", (string)null);
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.AgentRun", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<string>("ContextPackagePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("context_package_path");

                    b.Property<int?>("ContextPackageSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("context_package_size");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_ms");

                    b.Property<string>("GateReportPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("gate_report_path");

                    b.Property<string>("InputParams")
                        .HasColumnType("TEXT")
                        .HasColumnName("input_params");

                    b.Property<string>("OutputData")
                        .HasColumnType("TEXT")
                        .HasColumnName("output_data");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<string>("RunType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("run_type");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("running")
                        .HasColumnName("status");

                    b.Property<string>("TargetChapterId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("target_chapter_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RunType");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("agent_runs", (string)null);
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.AgentSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<string>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<string>("SessionData")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_data");

                    b.Property<string>("Title")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("新会话")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("agent_sessions", (string)null);
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.Chapter", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("chapter_number");

                    b.Property<string>("ContentPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content_path");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("draft")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("VolumeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("volume_id");

                    b.Property<int>("WordCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("word_count");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("idx_chapters_project");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_chapters_status");

                    b.HasIndex("VolumeId")
                        .HasDatabaseName("idx_chapters_volume");

                    b.ToTable("chapters", (string)null);
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.Character", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER")
                        .HasColumnName("age");

                    b.Property<string>("Alias")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("alias");

                    b.Property<string>("Appearance")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("appearance");

                    b.Property<string>("Background")
                        .HasColumnType("TEXT")
                        .HasColumnName("background");

                    b.Property<string>("CoreGoal")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("core_goal");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CurrentPowerLevel")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("current_power_level");

                    b.Property<string>("FirstAppearChapter")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("first_appear_chapter");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("gender");

                    b.Property<string>("InitialPowerLevel")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("initial_power_level");

                    b.Property<string>("LastAppearChapter")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_appear_chapter");

                    b.Property<string>("Motivation")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("motivation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Personality")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("personality");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<string>("Relationships")
                        .HasColumnType("TEXT")
                        .HasColumnName("relationships");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<string>("SpecialAbilities")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("special_abilities");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("idx_characters_project");

                    b.HasIndex("UserId");

                    b.ToTable("characters", (string)null);
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.ContentChunk", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("CharEnd")
                        .HasColumnType("INTEGER")
                        .HasColumnName("char_end");

                    b.Property<int>("CharStart")
                        .HasColumnType("INTEGER")
                        .HasColumnName("char_start");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("chunk_index");

                    b.Property<string>("ChunkText")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("chunk_text");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content_hash");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("document_id");

                    b.Property<int>("TokenCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("token_count");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "DocumentId");

                    b.HasIndex("DocumentId", "ChunkIndex")
                        .IsUnique();

                    b.ToTable("content_chunks", (string)null);
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.ContentDocument", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content_hash");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DocumentRole")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("document_role");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("text/plain")
                        .HasColumnName("mime_type");

                    b.Property<string>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.HasIndex("SourceType", "SourceId", "Version");

                    b.ToTable("content_documents", (string)null);
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.ContentVectorPoint", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ChunkId")
                        .HasColumnType("TEXT")
                        .HasColumnName("chunk_id");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("document_id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<string>("IndexStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("pending")
                        .HasColumnName("index_status");

                    b.Property<DateTime?>("IndexedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("indexed_at");

                    b.Property<string>("QdrantCollection")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("qdrant_collection");

                    b.Property<string>("QdrantPointId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("qdrant_point_id");

                    b.Property<string>("VectorModel")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("vector_model");

                    b.HasKey("Id");

                    b.HasIndex("ChunkId");

                    b.HasIndex("ChunkId", "DocumentId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("QdrantCollection", "QdrantPointId")
                        .IsUnique();

                    b.ToTable("content_vector_points", (string)null);
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.Foreshadow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int?>("Importance")
                        .HasColumnType("INTEGER")
                        .HasColumnName("importance");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("PayoffChapterId")
                        .HasColumnType("TEXT")
                        .HasColumnName("payoff_chapter_id");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<string>("SetupChapterId")
                        .HasColumnType("TEXT")
                        .HasColumnName("setup_chapter_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("planned")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("PayoffChapterId");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("idx_foreshadows_project");

                    b.HasIndex("SetupChapterId");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_foreshadows_status");

                    b.ToTable("foreshadows", (string)null);
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.ForeshadowEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("PlantedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("planted_at");

                    b.Property<string>("PlantedContext")
                        .HasColumnType("TEXT")
                        .HasColumnName("planted_context");

                    b.Property<string>("PlantedInChapter")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("planted_in_chapter");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(5)
                        .HasColumnName("priority");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("resolved_at");

                    b.Property<string>("ResolvedContext")
                        .HasColumnType("TEXT")
                        .HasColumnName("resolved_context");

                    b.Property<string>("ResolvedInChapter")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("resolved_in_chapter");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("planted")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("foreshadow_ledger", (string)null);
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.KnowledgeBase", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int?>("ChunkIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("chunk_index");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("entry_type");

                    b.Property<string>("ExtractionContext")
                        .HasColumnType("TEXT")
                        .HasColumnName("extraction_context");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<string>("SourceFileId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_file_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("manual")
                        .HasColumnName("source_type");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<int>("UsageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("usage_count");

                    b.Property<string>("VectorId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("vector_id");

                    b.Property<int>("Weight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(5)
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("knowledge_base", (string)null);
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.KnowledgeProcessingTask", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<int>("ExtractedEntriesCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("extracted_entries_count");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_path");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_size");

                    b.Property<int>("ProcessedChunks")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("processed_chunks");

                    b.Property<int>("Progress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("progress");

                    b.Property<string>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("single_pass")
                        .HasColumnName("strategy");

                    b.Property<int?>("TotalChunks")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_chunks");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("knowledge_processing_tasks", (string)null);
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.Material", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<string>("ContentType")
                        .HasColumnType("TEXT")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT")
                        .HasColumnName("file_path");

                    b.Property<string>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<int>("VectorChunkCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("vector_chunk_count");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("idx_materials_project");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_materials_user");

                    b.ToTable("materials", (string)null);
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.NovelProject", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CoreHook")
                        .HasColumnType("TEXT")
                        .HasColumnName("core_hook");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("cover_image_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Genre")
                        .HasColumnType("TEXT")
                        .HasColumnName("genre");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("draft")
                        .HasColumnName("status");

                    b.Property<string>("StorageProjectName")
                        .HasColumnType("TEXT")
                        .HasColumnName("storage_project_name");

                    b.Property<string>("SubGenre")
                        .HasColumnType("TEXT")
                        .HasColumnName("sub_genre");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<int>("WordCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("word_count");

                    b.HasKey("Id");

                    b.HasIndex("StorageProjectName")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("novel_projects", (string)null);
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.ProjectKnowledgeUsage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("FirstSeenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("first_seen_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("KnowledgeId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_id");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<string>("SourceRunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_run_id");

                    b.Property<string>("SourceSessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("imported")
                        .HasColumnName("status");

                    b.Property<int>("UsageCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("usage_count");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId", "ProjectId", "KnowledgeId")
                        .IsUnique();

                    b.ToTable("project_knowledge_usages", (string)null);
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.StoryConstitution", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CoreHook")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("core_hook");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("genre");

                    b.Property<string>("GenreProfile")
                        .HasColumnType("TEXT")
                        .HasColumnName("genre_profile");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<string>("ReaderPromise")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("reader_promise");

                    b.Property<string>("SubGenre")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("sub_genre");

                    b.Property<string>("Taboos")
                        .HasColumnType("TEXT")
                        .HasColumnName("taboos");

                    b.Property<string>("TargetAudience")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("target_audience");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("story_constitutions", (string)null);
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("ApiCallQuota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(10000)
                        .HasColumnName("api_call_quota");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<int>("StorageQuotaMb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(5120)
                        .HasColumnName("storage_quota_mb");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.UserSettings", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<bool>("AgentLoopAutoProceed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("agent_loop_auto_proceed");

                    b.Property<string>("AgentDefaultRisk")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Medium")
                        .HasColumnName("agent_default_risk");

                    b.Property<int>("AgentLoopMaxSteps")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(12)
                        .HasColumnName("agent_loop_max_steps");

                    b.Property<int>("DefaultChapterWordCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(3000)
                        .HasColumnName("default_chapter_word_count");

                    b.Property<string>("DefaultGenre")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("玄幻")
                        .HasColumnName("default_genre");

                    b.Property<string>("EmbeddingModel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("bge-small-zh-v1.5")
                        .HasColumnName("embedding_model");

                    b.Property<string>("EmbeddingProvider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("local")
                        .HasColumnName("embedding_provider");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("zh-CN")
                        .HasColumnName("language");

                    b.Property<string>("LlmApiKeyEncrypted")
                        .HasColumnType("TEXT")
                        .HasColumnName("llm_api_key_encrypted");

                    b.Property<string>("LlmBaseUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("llm_base_url");

                    b.Property<int>("LlmMaxTokens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(4096)
                        .HasColumnName("llm_max_tokens");

                    b.Property<string>("LlmModel")
                        .HasColumnType("TEXT")
                        .HasColumnName("llm_model");

                    b.Property<string>("LlmProvider")
                        .HasColumnType("TEXT")
                        .HasColumnName("llm_provider");

                    b.Property<float>("LlmTemperature")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.7f)
                        .HasColumnName("llm_temperature");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("dark")
                        .HasColumnName("theme");

                    b.HasKey("UserId");

                    b.ToTable("user_settings", (string)null);
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.Volume", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<int>("VolumeNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("volume_number");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("volumes", (string)null);
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.VolumeArc", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Act1Setup")
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT")
                        .HasColumnName("act1_setup");

                    b.Property<string>("Act2Confrontation")
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT")
                        .HasColumnName("act2_confrontation");

                    b.Property<string>("Act3Climax")
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT")
                        .HasColumnName("act3_climax");

                    b.Property<string>("Act4Resolution")
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT")
                        .HasColumnName("act4_resolution");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<string>("ConflictEscalation")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("conflict_escalation");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CurrentChapters")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("current_chapters");

                    b.Property<string>("KeyEvents")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("key_events");

                    b.Property<string>("MajorConflict")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("major_conflict");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("planned")
                        .HasColumnName("status");

                    b.Property<int?>("TargetChapters")
                        .HasColumnType("INTEGER")
                        .HasColumnName("target_chapters");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<int>("VolumeNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("volume_number");

                    b.Property<string>("VolumeTheme")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("volume_theme");

                    b.Property<string>("VolumeTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("volume_title");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ProjectId", "VolumeNumber")
                        .IsUnique();

                    b.ToTable("volume_arcs", (string)null);
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.WorldSettingEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("ChangeLog")
                        .HasColumnType("TEXT")
                        .HasColumnName("change_log");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FirstMentionedChapter")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("first_mentioned_chapter");

                    b.Property<string>("PreviousVersion")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("previous_version");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<string>("ReferencedChapters")
                        .HasColumnType("TEXT")
                        .HasColumnName("referenced_chapters");

                    b.Property<string>("SubCategory")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("sub_category");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("world_settings", (string)null);
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.AgentChatSummary", b =>
                {
                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.NovelProject", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.AgentSession", null)
                        .WithMany("ChatSummaries")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.AgentChatTurn", b =>
                {
                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.NovelProject", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.AgentSession", null)
                        .WithMany("ChatTurns")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.AgentMemory", b =>
                {
                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.NovelProject", "Project")
                        .WithMany("AgentMemories")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.User", "User")
                        .WithMany("AgentMemories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.AgentMemoryEvent", b =>
                {
                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.NovelProject", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.AgentMemoryVersion", b =>
                {
                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.NovelProject", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.AgentRun", b =>
                {
                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.NovelProject", "Project")
                        .WithMany("AgentRuns")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.AgentSession", b =>
                {
                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.NovelProject", "Project")
                        .WithMany("AgentSessions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.User", "User")
                        .WithMany("AgentSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.Chapter", b =>
                {
                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.NovelProject", "Project")
                        .WithMany("Chapters")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.Volume", "Volume")
                        .WithMany("Chapters")
                        .HasForeignKey("VolumeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Project");

                    b.Navigation("Volume");
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.Character", b =>
                {
                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.NovelProject", "Project")
                        .WithMany("Characters")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.ContentChunk", b =>
                {
                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.ContentDocument", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.ContentDocument", b =>
                {
                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.NovelProject", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.ContentVectorPoint", b =>
                {
                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.ContentChunk", null)
                        .WithMany()
                        .HasForeignKey("ChunkId", "DocumentId")
                        .HasPrincipalKey("Id", "DocumentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.ContentDocument", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.Foreshadow", b =>
                {
                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.Chapter", "PayoffChapter")
                        .WithMany("ForeshadowsPayoff")
                        .HasForeignKey("PayoffChapterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.NovelProject", "Project")
                        .WithMany("Foreshadows")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.Chapter", "SetupChapter")
                        .WithMany("ForeshadowsSetup")
                        .HasForeignKey("SetupChapterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PayoffChapter");

                    b.Navigation("Project");

                    b.Navigation("SetupChapter");
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.ForeshadowEntry", b =>
                {
                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.NovelProject", "Project")
                        .WithMany("ForeshadowEntries")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.KnowledgeBase", b =>
                {
                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.NovelProject", "Project")
                        .WithMany("KnowledgeBases")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.KnowledgeProcessingTask", b =>
                {
                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.NovelProject", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.Material", b =>
                {
                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.NovelProject", "Project")
                        .WithMany("Materials")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.User", "User")
                        .WithMany("Materials")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.NovelProject", b =>
                {
                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.User", "User")
                        .WithMany("NovelProjects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.ProjectKnowledgeUsage", b =>
                {
                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.KnowledgeBase", null)
                        .WithMany()
                        .HasForeignKey("KnowledgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.NovelProject", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.StoryConstitution", b =>
                {
                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.NovelProject", "Project")
                        .WithOne("StoryConstitution")
                        .HasForeignKey("TM.Web.NovelAgentWeb.Data.Entities.StoryConstitution", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.UserSettings", b =>
                {
                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.User", "User")
                        .WithOne("UserSettings")
                        .HasForeignKey("TM.Web.NovelAgentWeb.Data.Entities.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.Volume", b =>
                {
                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.NovelProject", "Project")
                        .WithMany("Volumes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.VolumeArc", b =>
                {
                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.NovelProject", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.WorldSettingEntry", b =>
                {
                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.NovelProject", "Project")
                        .WithMany("WorldSettingEntries")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TM.Web.NovelAgentWeb.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.Chapter", b =>
                {
                    b.Navigation("ForeshadowsPayoff");

                    b.Navigation("ForeshadowsSetup");
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.ContentDocument", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.NovelProject", b =>
                {
                    b.Navigation("AgentMemories");

                    b.Navigation("AgentRuns");

                    b.Navigation("AgentSessions");

                    b.Navigation("Chapters");

                    b.Navigation("Characters");

                    b.Navigation("ForeshadowEntries");

                    b.Navigation("Foreshadows");

                    b.Navigation("KnowledgeBases");

                    b.Navigation("Materials");

                    b.Navigation("StoryConstitution");

                    b.Navigation("Volumes");

                    b.Navigation("WorldSettingEntries");
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.User", b =>
                {
                    b.Navigation("AgentMemories");

                    b.Navigation("AgentSessions");

                    b.Navigation("Materials");

                    b.Navigation("NovelProjects");

                    b.Navigation("UserSettings");
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.AgentSession", b =>
                {
                    b.Navigation("ChatSummaries");

                    b.Navigation("ChatTurns");
                });

            modelBuilder.Entity("TM.Web.NovelAgentWeb.Data.Entities.Volume", b =>
                {
                    b.Navigation("Chapters");
                });
#pragma warning restore 612, 618
        }
    }
}
