using System.ComponentModel.DataAnnotations;

namespace TM.Web.NovelAgentWeb.DTOs;

/// <summary>
/// Request DTO for creating a knowledge entry.
/// </summary>
public class CreateKnowledgeRequest
{
    [Required]
    public string ProjectId { get; set; } = null!;

    [Required]
    public string EntryType { get; set; } = null!;

    [Required]
    public string Title { get; set; } = null!;

    [Required]
    public string Content { get; set; } = null!;

    public List<string>? Tags { get; set; }
    public int? Weight { get; set; }
    public string? IdempotencyKey { get; set; }
}

/// <summary>
/// Internal request for knowledge created by the server-side upload/extraction pipeline.
/// Source identifiers are generated by the backend, not accepted from public clients.
/// </summary>
public class CreateExtractedKnowledgeRequest
{
    [Required]
    public string ProjectId { get; set; } = null!;

    [Required]
    public string EntryType { get; set; } = null!;

    [Required]
    public string Title { get; set; } = null!;

    [Required]
    public string Content { get; set; } = null!;

    public List<string>? Tags { get; set; }
    public int? Weight { get; set; }
    public string SourceUploadTaskId { get; set; } = null!;
    public int? ChunkIndex { get; set; }
    public string? ExtractionContext { get; set; }
    public string? IdempotencyKey { get; set; }
}

/// <summary>
/// Request DTO for updating a knowledge entry.
/// </summary>
public class UpdateKnowledgeRequest
{
    public string? EntryType { get; set; }
    public string? Title { get; set; }
    public string? Content { get; set; }
    public List<string>? Tags { get; set; }
    public int? Weight { get; set; }
    public bool? IsArchived { get; set; }
}

public class CreateKnowledgeDirectoryRequest
{
    [Required]
    public string Name { get; set; } = null!;

    public string? IdempotencyKey { get; set; }
}

public class UpdateKnowledgeDirectoryRequest
{
    [Required]
    public string Name { get; set; } = null!;
}

public class KnowledgeDirectoryResponse
{
    public string Key { get; set; } = null!;
    public string Name { get; set; } = null!;
    public string Description { get; set; } = "";
    public bool IsSystem { get; set; }
    public int EntryCount { get; set; }
    public DateTime? CreatedAt { get; set; }
    public DateTime? UpdatedAt { get; set; }
}

/// <summary>
/// Request DTO for semantic search in knowledge base.
/// </summary>
public class SearchKnowledgeRequest
{
    [Required]
    public string ProjectId { get; set; } = null!;

    [Required]
    public string Query { get; set; } = null!;

    public int TopK { get; set; } = 10;

    public string? EntryType { get; set; }
}

/// <summary>
/// Request DTO for recording knowledge usage in the current project context.
/// </summary>
public class IncrementKnowledgeUsageRequest
{
    [Required]
    public string ProjectId { get; set; } = null!;

    public string? SessionId { get; set; }
    public string? RunId { get; set; }
    public string? IdempotencyKey { get; set; }
}

/// <summary>
/// Response DTO for knowledge entry.
/// </summary>
public class KnowledgeResponse
{
    public string Id { get; set; } = null!;
    public string? UsageProjectId { get; set; }
    public string? SourceProjectId { get; set; }
    public string? SourceProjectTitle { get; set; }
    public string SourceType { get; set; } = "manual";
    public string? SourceUploadTaskId { get; set; }
    public int? ChunkIndex { get; set; }
    public string? ExtractionContext { get; set; }
    public string EntryType { get; set; } = null!;
    public string Title { get; set; } = null!;
    public string Content { get; set; } = null!;
    public List<string> Tags { get; set; } = new();
    public int Weight { get; set; } = 5;
    public int UsageCount { get; set; }
    public DateTime CreatedAt { get; set; }
    public bool IsArchived { get; set; }
    public string? VectorId { get; set; }
    public string ProjectUsageStatus { get; set; } = "none";
    public int ProjectUsageCount { get; set; }
    public DateTime? ProjectLastUsedAt { get; set; }
    public List<KnowledgeProjectUsageResponse> ProjectUsages { get; set; } = new();
    public List<KnowledgeConstraintEvidenceResponse> ConstraintEvidence { get; set; } = new();
}

/// <summary>
/// Per-project usage summary for a knowledge entry.
/// </summary>
public class KnowledgeProjectUsageResponse
{
    public string ProjectId { get; set; } = null!;
    public string ProjectTitle { get; set; } = null!;
    public string Status { get; set; } = "imported";
    public int UsageCount { get; set; }
    public DateTime FirstSeenAt { get; set; }
    public DateTime? LastUsedAt { get; set; }
}

public class KnowledgeConstraintEvidenceResponse
{
    public string KnowledgeId { get; set; } = null!;
    public string Title { get; set; } = "";
    public string EntryType { get; set; } = "";
    public string Subject { get; set; } = "";
    public string ConstraintLevel { get; set; } = "";
    public string PackagePolicy { get; set; } = "";
    public string EvidenceStatus { get; set; } = "";
    public string GateStatus { get; set; } = "";
    public string ProjectId { get; set; } = "";
    public string ProjectTitle { get; set; } = "";
    public string ChapterId { get; set; } = "";
    public string FactSnapshotId { get; set; } = "";
    public int FactSnapshotVersion { get; set; }
    public DateTime CreatedAt { get; set; }
    public List<string> AllowedTerms { get; set; } = new();
    public List<string> ForbiddenTerms { get; set; } = new();
    public List<string> Violations { get; set; } = new();
}

/// <summary>
/// Response DTO for semantic search result.
/// </summary>
public class KnowledgeSearchResult
{
    public string Id { get; set; } = null!;
    public string SourceType { get; set; } = "manual";
    public string? SourceUploadTaskId { get; set; }
    public int? ChunkIndex { get; set; }
    public string? ExtractionContext { get; set; }
    public string EntryType { get; set; } = null!;
    public string Title { get; set; } = null!;
    public string Content { get; set; } = null!;
    public float Score { get; set; }
    public string ProjectUsageStatus { get; set; } = "none";
    public int ProjectUsageCount { get; set; }
    public DateTime? ProjectLastUsedAt { get; set; }
}
